import type { Metadata } from "next";
import "./globals.css";

import { NavBar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

// Import Inter font
import { Inter, Charm } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark max-w-[100vw] overflow-x-hidden" lang="en">
      <body className={`${inter.className}  antialiased dark `}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
